In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go

df = pd.read_csv("data/Shared_data_responses_demographics.csv")

df

,UserIP_Anonymized,Scenario,survey.age,survey.gender,survey.education,survey.political,survey.religious,country_code,Outcome,Continent
0,0002ae2d,Footbridge,19,Women,College,0.56,0.00,GB,0,Europe
1,0002ae2d,Loop,19,Women,College,0.56,0.00,GB,1,Europe
2,0002ae2d,Switch,19,Women,College,0.56,0.00,GB,1,Europe
3,00065336,Footbridge,19,Men,College,0.00,0.68,FR,1,Europe
4,00065336,Loop,19,Men,College,0.00,0.68,FR,0,Europe
...,...,...,...,...,...,...,...,...,...,...
59154,ffef6123,Footbridge,27,Men,College,0.34,0.53,SG,0,Asia
59155,ffef6123,Loop,23,Men,College,1.00,0.00,SG,1,Asia
59156,ffef6123,Loop,27,Men,College,0.34,0.53,SG,1,Asia
59157,ffef6123,Switch,23,Men,College,1.00,0.00,SG,1,Asia
59158,ffef6123,Switch,27,Men,College,0.34,0.53,SG,1,Asia

In [2]:
df["Scenario"] = df["Scenario"].map({'Footbridge': 0, 'Loop': 1, 'Switch': 2})
df["survey.gender"] = df["survey.gender"].map({'Men': 0, 'Women': 1})
df["survey.education"] = df["survey.education"].map({'College': 0, 'No College': 1})

In [3]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

[dfTrain, dfTest] = train_test_split(df, test_size=0.3, random_state=42)

xTrain = dfTrain[['Scenario', 'survey.age', 'survey.gender', 'survey.education', 'survey.political', 'survey.religious']].values
xTest = dfTest[['Scenario', 'survey.age', 'survey.gender', 'survey.education', 'survey.political', 'survey.religious']].values

yTrain = dfTrain['Outcome'].values
yTest = dfTest['Outcome'].values

linRegr = linear_model.LinearRegression()
linRegr.fit(xTrain, yTrain)

print("\tTrain R²: ", linRegr.score(xTrain, yTrain))
print("\tTest R²: ", linRegr.score(xTest, yTest))

	Train R²:  0.10929688154613448
	Test R²:  0.10951259155743154

In [4]:
def calcCorrectness(x, y):
    a = 0
    for i in range(len(x)):
        if round(linRegr.predict(x[0].reshape(1, -1))[0]) == y[i]:
            a+=1
    print(round(a/len(x) * 100, 2), "%")
    
calcCorrectness(xTest, yTest)
calcCorrectness(xTrain, yTrain)

68.55 %
30.97 %